## Matlab style file organization, one function per file
from FGN_layer import FGN_layer
from Feedforward_Hybrid_First_net import Feedforward_Hybrid_First_net
from Feedforward_Hybrid_Last_net import Feedforward_Hybrid_Last_net
from Feedforward_First_Centers_net import Feedforward_First_Centers_net
from Feedforward_FGN_net import Feedforward_FGN_net
from Feedforward_Classic_net import Feedforward_Classic_net
from convert_classic_to_fgn import convert_classic_to_fgn
from sigmas_loss import sigmas_loss
from fgn_cross_ent_loss import fgn_cross_ent_loss
from def_fgn_cross_ent_loss import def_fgn_cross_ent_loss
from adjust_sigma_pred_func import adjust_sigma_pred_func
from FGSM_attack_untargeted import FGSM_attack_untargeted
from FGSM_attack_targeted import FGSM_attack_targeted
from full_FGSM_attack import full_FGSM_attack
from plot_centers_histories import plot_centers_histories
from plot_sigmas_histories import plot_sigmas_histories

__version__ = '0.01'